In [5]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
a = [1,2,3,4, 3.5,]
a

[1, 2, 3, 4, 3.5]

In [7]:
np.array(a)

array([1. , 2. , 3. , 4. , 3.5])

In [9]:
l =[[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr = np.arange(1,11,3)
arr

array([ 1,  4,  7, 10])

In [16]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [7]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
arr = np.ones((4,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
arr = np.linspace(1,5,6)
arr

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [12]:
np.random.rand(5)

array([0.43616965, 0.23470288, 0.20517796, 0.78004614, 0.97766267])

In [15]:
arr = np.random.randint(5)
arr

3

In [17]:
arr = np.random.randint(10,20,10)
arr

array([12, 10, 17, 10, 17, 10, 14, 14, 10, 17], dtype=int32)

In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.shape

(3, 3)

In [20]:
arr.size

9

In [21]:
arr.dtype

dtype('int64')

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr.min()

np.int64(1)

In [25]:
arr.max()

np.int64(9)

In [26]:
arr.sum()

np.int64(45)

In [28]:
np.sum(arr, axis = 0)

array([12, 15, 18])

In [29]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [32]:
arr.mean()

np.float64(5.0)

In [33]:
arr.std()

np.float64(2.581988897471611)

In [34]:
arr.argmax()

np.int64(8)

In [35]:
arr.argmin()

np.int64(0)

In [36]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [37]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])