In [4]:
import numpy as np

In [6]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[6]

np.int64(17)

In [9]:
arr[2:5]

array([13, 14, 15])

In [10]:
arr[:5]

array([11, 12, 13, 14, 15])

In [11]:
arr[5:]

array([16, 17, 18, 19, 20])

In [12]:
arr[2::2]

array([13, 15, 17, 19])

In [16]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [20]:
arr[0]

array([1, 2, 3, 4, 5])

In [22]:
arr[0,0]

np.int64(1)

In [24]:
arr[0,4]

np.int64(5)

In [25]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [26]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [34]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [35]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [36]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])