In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([5,6,7,8,9])

In [4]:
arr2 = a1 + a2
arr2

array([ 6,  8, 10, 12, 14])

In [5]:
arr3 = a2 - a1
arr3

array([4, 4, 4, 4, 4])

In [6]:
arr4 = a2 * a1
arr4

array([ 5, 12, 21, 32, 45])

In [7]:
arr5 = a2 / a1
arr5

array([5.        , 3.        , 2.33333333, 2.        , 1.8       ])

In [8]:
l =[10,20,30,40]
arr = np.array(l)

In [9]:
arr + 10

array([20, 30, 40, 50])

In [10]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [13]:
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [16]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [17]:
A

array([[1, 2],
       [3, 4]])

In [18]:
B

array([[5, 6],
       [7, 8]])

In [19]:
A @ B

array([[19, 22],
       [43, 50]])

In [20]:
mul = np.dot(A,B)
mul

array([[19, 22],
       [43, 50]])

In [21]:
A.T

array([[1, 3],
       [2, 4]])

In [22]:
A

array([[1, 2],
       [3, 4]])

In [23]:
B

array([[5, 6],
       [7, 8]])

In [24]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [25]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [28]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [30]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [31]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [32]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [33]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])