In [26]:
import numpy as np


# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [8]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [6]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [10]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [11]:
#Find the highest Science mark.
maximum = data[:,1]
maximum.max()

np.int64(92)

In [14]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [28]:
#Increase Math marks of all students by 5.
a = data[:,1] + 5
a

array([90, 97, 81, 70, 95])

In [32]:
#Find how many students are younger than 19.
len(data[data[:,0] < 19])


3

In [35]:
#Calculate the average marks in each subject (column-wise mean).
np.min(data[:,1:],axis=0)

array([65, 70])

In [36]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [39]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])